spring:
  application:
    name: movie
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: thiendev58@gmail.com
    password: yjpkzqmheitnztgn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
file:
  upload:
    video-dir: uploads/videos
    image-dir: uploads/images

jwt:
  secret: 4b8f99cc3ce393b096697e9ac59eee5461a6a5ca2d9d72ab945e0366159e0888
  expiration: 2592000

app:
  frontend.url: http://localhost:4200
